import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { JobsProvider } from "./contexts/jobs-provider";
import { Job } from "@/lib/definitions";
import redis from "@/lib/redis";
import prisma from "@/lib/prisma";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const jobs = await getJobs();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <JobsProvider initialJobs={jobs}>{children}</JobsProvider>
      </body>
    </html>
  );
}

const getJobs = async () => {
  const keys = await redis.keys("user1:*");
  const jobs: Job[] = [];
  const prismaJobs = await prisma.job.findMany({
    where: {
      userId: "user1",
    },
  });

  for (const job of prismaJobs) {
    jobs.push({
      id: job.id,
      userId: job.userId,
      status: job.status,
      aspectRatio: job.aspectRatio,
      createdAt: job.createdAt.getTime(),
      progress: 100,
    });
  }

  for (const key of keys) {
    const job = (await redis.json.get(key)) as Job;
    jobs.push(job);
  }

  return jobs.sort((a, b) => b.createdAt - a.createdAt);
};
